name: Hiero Solo Action
description: Setup a Hiero Solo
author: Hiero Ledger

# Branding
branding:
  icon: "share-2"
  color: "black"

# Inputs
inputs:
  installMirrorNode:
    description: "Defines if a mirror node should be installed"
    required: true
    default: false
    type: boolean
  hieroVersion:
    description: "Version of Hiero consensus node to be used"
    required: false
    default: "v0.58.10"
  mirrorNodeVersion:
    description: "Version of the mirror node to be used"
    required: false
    default: "v0.133.0"
  mirrorNodePortRest:
    description: "Port for Mirror Node REST API"
    required: false
    default: "5551"
  mirrorNodePortGrpc:
    description: "Port for Mirror Node gRPC"
    required: false
    default: "5600"
  mirrorNodePortWeb3Rest:
    description: "Port for Mirror Node WEB3 REST"
    required: false
    default: "8545"
  installRelay:
    description: "Install JSON-RPC-Relay"
    required: false
    default: false
    type: boolean
  relayPort:
    description: "Port for JSON-RPC-Relay"
    required: false
    default: "7546"

#  Outputs
outputs:
  accountId:
    description: "Account ID of the generated ED25519 account (default for simplicity)"
  publicKey:
    description: "Public key of the generated ED25519 account (default for simplicity)"
  privateKey:
    description: "Private key of the generated ED25519 account (default for simplicity)"
  ecdsaAccountId:
    description: "ECDSA account id of generated account"
  ecdsaPublicKey:
    description: "ECDSA public key of generated account"
  ecdsaPrivateKey:
    description: "ECDSA private key of generated account"
  ed25519AccountId:
    description: "ED25519 account id of generated account"
  ed25519PublicKey:
    description: "ED25519 public key of generated account"
  ed25519PrivateKey:
    description: "ED25519 private key of generated account"

runs:
  using: node20
  main: dist/index.js
  post: dist/post.js
